steps:
- name: 'maven:3.6.3-jdk-11'
  entrypoint: 'mvn'
  args: ['clean', 'install']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'app'
    - 'deploy'
    - '--project'
    - 'scenic-energy-404510'
    - '--version'
    - '$BUILD_ID'
    - '--promote'
    - '--stop-previous-version'
    - '--quiet'
    - '--verbosity=info'
    - '--image-url=gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID'

options:
  logging: CLOUD_LOGGING_ONLY
